<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4wCVcTV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4wCVcTV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4wCVcTV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4wCVcTV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4wCVcTV\App_KernelDevDebugContainer([
    'container.build_hash' => '4wCVcTV',
    'container.build_id' => '2070cf1c',
    'container.build_time' => 1731238800,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4wCVcTV');
