<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQXWaANc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQXWaANc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQXWaANc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQXWaANc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQXWaANc\App_KernelDevDebugContainer([
    'container.build_hash' => 'QXWaANc',
    'container.build_id' => '200270c8',
    'container.build_time' => 1732206607,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQXWaANc');
