<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKmFTsnA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKmFTsnA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKmFTsnA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKmFTsnA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKmFTsnA\App_KernelDevDebugContainer([
    'container.build_hash' => 'KmFTsnA',
    'container.build_id' => '30b4cfc6',
    'container.build_time' => 1729690524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKmFTsnA');
